# Generated by Django 5.1.4 on 2025-03-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='description',
            new_name='usage',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='symptoms',
            field=models.TextField(),
        ),
    ]
